### ISSUE TITLE
Consider disabling StyleCI for this repo!

### ISSUE THREAD

**Issue by irazasyed** [laravel-notification-channels/skeleton#19]
Since this is a template with placeholders like this for [example](https://github.com/laravel-notification-channels/skeleton/blob/master/src/ServiceNameChannel.php#L3-L5). StyleCI is identifying them as some [issues](https://github.styleci.io/analyses/86Jova) and hence, the repo is getting an X and the first impression of looking at the repo implies there are issues with the project.

**Comment by irazasyed** [comment]
Or if it's a must to keep, perhaps we should consider removing the `:` char as the string is anyway unique and won't replace anything else within the template (we can make sure about this ofc).

**Comment by atymic** [comment]
I don't think styleCI needed since it's always going to fail with the placeholders (as they are ATM). 
I do think there's value in switching the placeholders to ones that are syntactically correct, as it means we can run linters/tests/etc on the repo.

**Comment by atymic** [comment]
I've disabled styleCI.
