### ISSUE TITLE
Naming consistency?

### ISSUE THREAD

**Issue by cs475x** [laravel-notification-channels/skeleton#2]
Right now there are two terms used to describe a notification:

- `Notification` (obviously) - e.g. [`CouldNotSendNotification`](https://github.com/laravel-notification-channels/skeleton/blob/d9d64fd50417ee5aea79d81ea20701a74e031fb2/src/Exceptions/CouldNotSendNotification.php)
- `Message` - e.g. [`MessageWasSent`](https://github.com/laravel-notification-channels/skeleton/blob/d9d64fd50417ee5aea79d81ea20701a74e031fb2/src/Events/MessageWasSent.php) & [`SendingMessage`](https://github.com/laravel-notification-channels/skeleton/blob/d9d64fd50417ee5aea79d81ea20701a74e031fb2/src/Events/SendingMessage.php)

Would it not be better if everything were described as a `Notification` instead of a `Message` or a mix of the two?

**Comment by themsaid** [comment]
Well in Laravel a Notification is different than a Message, a notification contains several formats (messages).

So in a single notification you can send multiple messages (sms, mail, web notifications, etc..).
